<a href="https://colab.research.google.com/github/IAmSuyogJadhav/fastai/blob/master/PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Learning PyTorch
from [here](https://www.kaggle.com/ashishpatel26/zero-to-hero-in-pytorch-ml-dl-rl/notebook).

## Install PyTorch

### Find CUDA Version

In [3]:
!nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148


### Install for with pip for Python 3.6 and CUDA 9.2

In [6]:
!pip3 install http://download.pytorch.org/whl/cu92/torch-0.4.1-cp36-cp36m-linux_x86_64.whl
!pip3 install torchvision

    100% |████████████████████████████████| 512.6MB 105.2MB/s 
tcmalloc: large alloc 1073750016 bytes == 0x57860000 @  0x7f442d8e12a4 0x594e17 0x626104 0x51190a 0x4f5277 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x510c78 0x5119bd 0x4f5277 0x4f3338 0x510fb0 0x5119bd 0x4f6070 0x4f3338 0x510fb0 0x5119bd 0x4f6070

    100% |████████████████████████████████| 61kB 2.2MB/s 
    100% |████████████████████████████████| 2.0MB 7.5MB/s 
  Found existing installation: Pillow 4.0.0
    Uninstalling Pillow-4.0.0:
      Successfully uninstalled Pillow-4.0.0


## The basics

In [0]:
import numpy as np
import torch

In [11]:
x = torch.empty(5, 3)  # Uninitialized matrix
print(x)

tensor([[3.4976e-37, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.3520e+22, 4.2094e+21, 5.2593e+22],
        [1.0559e-08, 5.2708e-08, 2.6223e-09],
        [2.1236e+20, 3.3356e-09, 1.3563e-19]])


In [12]:
x.numpy()  # Convert to Numpy array

array([[3.4975692e-37, 0.0000000e+00, 4.4841551e-44],
       [0.0000000e+00,           nan, 0.0000000e+00],
       [1.3519505e+22, 4.2094031e+21, 5.2593050e+22],
       [1.0558825e-08, 5.2708145e-08, 2.6222546e-09],
       [2.1236363e+20, 3.3355942e-09, 1.3563115e-19]], dtype=float32)

In [14]:
x.size()  # returns SHAPE

torch.Size([5, 3])

From Numpy to Tensor:

In [16]:
a = np.array([[3, 4], [4, 3]])
b = torch.from_numpy(a)
print(b)

tensor([[3, 4],
        [4, 3]])


### Tensor generators

In [17]:
torch.rand(5, 3)  # Random values

tensor([[0.2867, 0.5346, 0.3889],
        [0.5715, 0.4647, 0.0837],
        [0.5966, 0.4471, 0.9899],
        [0.0984, 0.5792, 0.3462],
        [0.5535, 0.6803, 0.2708]])

In [19]:
torch.zeros(5, 3, dtype=torch.int8)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int8)

In [20]:
torch.ones(5, 3, dtype=torch.float32)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [22]:
x = torch.tensor([2, 4, 5, 6.6])
print(x)

tensor([2.0000, 4.0000, 5.0000, 6.6000])


### `.new_`* methods
All of the methods that start with .new_* create a _new_ tensor, with the same `dtype` and `device` as the original tensor. 
- `.new_tensor(data)`: Data is `array-like`
-  `.new_full(shape, fill_value)`
- `.new_zeros(shape)`
- `.new_ones(shape)`
- `.new_empty(shape)`

In [29]:
x.new_ones(5, 3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [32]:
x.new_empty(5)

tensor([0.0000, 0.0000, 0.0000, 0.0000,    nan])

### `.*_like()` methods

In [33]:
torch.randn_like(x)

tensor([-0.3873, -0.1745,  0.6347, -0.5655])

In [34]:
torch.zeros_like(x)

tensor([0., 0., 0., 0.])

### Basic Tensor Ops

Algebra: Use the overloaded operators (+, -, *, /) OR
- `torch.add()`
- `torch.sub()`
- `torch.mul()`
- `torch.div()`

In [54]:
x = torch.rand(5, 4)
y = torch.rand(1, 4)
print(x + y)  # Broadcasting will occur here for the addition...
torch.mul(x, y)  # ...and for the multiplication too

tensor([[0.5575, 0.5594, 1.8261, 0.4196],
        [0.8908, 0.7681, 1.4332, 0.0790],
        [0.2040, 0.6495, 1.7331, 0.9754],
        [0.5867, 1.0843, 1.4618, 0.6644],
        [0.8545, 0.4693, 1.2277, 0.7880]])


tensor([[0.0358, 0.0733, 0.8314, 0.0229],
        [0.0606, 0.1171, 0.4543, 0.0009],
        [0.0096, 0.0922, 0.7422, 0.0586],
        [0.0380, 0.1834, 0.4818, 0.0386],
        [0.0579, 0.0544, 0.2570, 0.0466]])

In [55]:
torch.div(y, x)

tensor([[0.1534, 0.5996, 1.1082, 0.1811],
        [0.0908, 0.3755, 2.0282, 4.3986],
        [0.5709, 0.4768, 1.2414, 0.0706],
        [0.1447, 0.2398, 1.9124, 0.1072],
        [0.0950, 0.8078, 3.5847, 0.0889]])

the `torch.*` algebraic operations are also available directly as `tensor.*`

In [56]:
x.sub(y)

tensor([[ 0.4092,  0.1400, -0.0937,  0.2910],
        [ 0.7425,  0.3487, -0.4866, -0.0497],
        [ 0.0557,  0.2301, -0.1866,  0.8468],
        [ 0.4384,  0.6649, -0.4580,  0.5357],
        [ 0.7062,  0.0499, -0.6921,  0.6594]])

`tensor.*_` algebraic operations are **inplace** versions of corresponding operations. Thus, they will modify the `tensor` inplace.

In [0]:
a = torch.ones(5, 4)
b = torch.ones(1, 4)

In [71]:
print(a.mul(b))
a.sub_(b)
a  # Gets modified

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

_In general, the inplace variant of a function_ `.func()` _in PyTorch is_ `.func_()`

### Basic Manipulation

Supports Numpy-style indexing

In [63]:
x = torch.randn(5, 4)
x[:, 2]

tensor([ 0.6829,  0.0904, -0.3956,  0.3183, -1.7091])

However, it doesn't support negative step currently. 

In [72]:
x[::-1]  
# ValueError: negative step not yet supported

ValueError: ignored

In [73]:
ls

sample_data/
